import type { Metadata } from 'next'
import './globals.css'

import { ToastProvider } from '@/contexts/toastContext'
import { NotificationProvider } from '@/contexts/notificationContext'

export const metadata: Metadata = {
  title: 'Elias Utmattad AB',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <body>
      <NotificationProvider>
	<ToastProvider>
	  <main>{children}</main>
	</ToastProvider>
      </NotificationProvider>
    </body>
  )
}
